version: "3.5"

services:
  web:
    image: drello-backend
    container_name: drello-backend-api
    ports:
      - "8080:8080"

    depends_on: 
      - "postgres"
      - "memcached"

  memcached:
    container_name: memcached_container
    image: 'bitnami/memcached:latest'
    ports:
      - "11211:11211"
  
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: drello_db
      POSTGRES_USER: drello_user
      POSTGRES_PASSWORD: drello1234
      PGDATA: /data/postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped