server: {
  ip: 0.0.0.0,
  port: 8080,
  mode : release,
}

logger: {
  logfile: stdout,
  level: debug,
}

database: {
  dbms: postgres,
  #host: postgres,
  host: localhost,
  user: drello_user,
  password: drello1234,
  name: drello_db,
  sslmode: disable
}

frontend: {
  protocol: http,
  ip: localhost,
  port: 5555,
  #public_dir задается в переменной окружения

  #относительно public_dir
  avatar_dir: /img/avatar,
  default_avatar: /img/default_avatar.png
}

cors: {
  allowed_origins: [
    http://89.208.197.150,
    https://89.208.197.150,
    http://localhost,
    http://localhost:5757,
    http://localhost:5555,
    https://localhost,
    https://localhost:5757,
    http://drello.works,
    https://drello.works,
  ]

  #добавить 5757 порт для запросов с доки
}