board: {
  name: Планирование проекта
}

labels: {
  Планирование: orange,
  Инфраструктура: green,
}

columns: {
  Список задач: {
    position: [0.0],
    Завести git-репозиторий: {
      position: [0.0],
      labels: [Инфраструктура],
    },

    Обсудить дизайн: {
      position: [1.0],
      labels: [Планирование],
    },

    Определиться со стэком: {
      position: [2.0],
      labels: [Планирование, Инфраструктура],
    },

    Продумать API: {
      position: [3.0],
      labels: [Планирование, Инфраструктура],
    },

    Назначить задачи на ближайший спринт: {
      position: [4.0],
      labels: [Планирование],
    },

  },
  В разработке: {
    position: [1.0],
  },
  Ревью: {
    position: [2.0],
  },
  Тестирование: {
    position: [3.0],
  },
  Деплой: {
    position: [4.0],
  },
  Готово: {
    position: [5.0],
  },
}
