name: Docker-way build

on:
  push:
    branches: [ci_cd]
  pull_request:
    branches: [ci_cd]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: golangci/golangci-lint-action@v1.0.0
      - name: Run linters
        run: make run-linter
    
  test:
    needs: linter
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Run unit-tests
       run: make test-coverpkg

     - name: Check coverage
       run: make check-summary

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: DockerHub login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Create Builder, application images
        run: |
          docker build -t drello-builder -f docker/builder.Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_REPO }}:session-${GITHUB_SHA::8} -f docker/session.Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_REPO }}:user-${GITHUB_SHA::8} -f docker/user.Dockerfile .
          docker build -t ${{ secrets.DOCKERHUB_REPO }}:api-${GITHUB_SHA::8} -f docker/api.Dockerfile .
      
      - name: Push application images
        run: |
          docker push ${{ secrets.DOCKERHUB_REPO }}:session-${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_REPO }}:user-${GITHUB_SHA::8}
          docker push ${{ secrets.DOCKERHUB_REPO }}:api-${GITHUB_SHA::8}
          





